import { documentParagraphs, initialReviewIssues } from "./mockReview";
import type { ReviewStreamingStage, ReviewTask } from "./reviewTypes";

function cloneParagraphs() {
  return documentParagraphs.map((paragraph) => ({ ...paragraph }));
}

function cloneIssues() {
  return initialReviewIssues.map((issue) => structuredClone(issue));
}

export function createSeedReviewTasks(): ReviewTask[] {
  const totalParagraphs = documentParagraphs.length;
  return [
    {
      id: "doc-001",
      name: "南京综合楼施工组织设计.pdf",
      project: "南京综合楼项目",
      uploader: "张工",
      updatedAt: "2026-07-09 09:12",
      status: "ready",
      issueCount: 4,
      mode: "review",
      paragraphs: cloneParagraphs(),
      issues: cloneIssues(),
      streamStageIndex: 0,
      streamStageType: "structure-restoration",
      streamAgentKey: "structure-restoration",
      streamParagraphIndex: 1,
      streamParagraphTotal: totalParagraphs,
      streamCurrentParagraphId: "p-001",
      streamParagraphLabel: "一、工程概况",
    },
    {
      id: "doc-002",
      name: "塔吊专项施工方案.docx",
      project: "南京综合楼项目",
      uploader: "李工",
      updatedAt: "2026-07-08 18:43",
      status: "reviewing",
      issueCount: 0,
      mode: "revise",
      paragraphs: cloneParagraphs(),
      issues: cloneIssues(),
      streamStageIndex: 3,
      streamStageType: "rule-review",
      streamAgentKey: "construction-review",
      streamParagraphIndex: 3,
      streamParagraphTotal: totalParagraphs,
      streamCurrentParagraphId: "p-003",
      streamParagraphLabel: "三、塔吊安装与附着",
    },
    {
      id: "doc-003",
      name: "脚手架专项方案（整改版）.pdf",
      project: "西湖机电安装项目",
      uploader: "王工",
      updatedAt: "2026-07-07 15:20",
      status: "completed",
      issueCount: 6,
      mode: "review",
      paragraphs: cloneParagraphs(),
      issues: cloneIssues(),
      streamStageIndex: 0,
      streamStageType: "result-packaging",
      streamAgentKey: "report-generation",
      streamParagraphTotal: totalParagraphs,
    },
    {
      id: "doc-004",
      name: "临时用电方案（初稿）.pdf",
      project: "东苑住宅项目",
      uploader: "陈工",
      updatedAt: "2026-07-09 08:20",
      status: "uploaded",
      issueCount: 0,
      mode: "revise",
      paragraphs: cloneParagraphs(),
      issues: cloneIssues(),
      streamStageIndex: 0,
      streamStageType: "structure-restoration",
      streamAgentKey: "structure-restoration",
      streamParagraphTotal: totalParagraphs,
    },
  ];
}

export const mockStreamingStages: ReviewStreamingStage[] = [
  {
    id: "upload",
    stageType: "ocr",
    title: "建立审查任务",
    detail: "已接收文件，正在创建文档解析任务。",
    progress: 12,
    agentLabel: "PaddleOCR-VL",
    outlineItems: [],
    documentSnippets: ["正在读取文件元数据与项目基础信息。"],
    issueSummaries: [],
  },
  {
    id: "parse",
    stageType: "structure-restoration",
    title: "解析文档结构",
    detail: "识别章节、段落、表格与可锚定文本位置。",
    progress: 28,
    agentKey: "structure-restoration",
    agentLabel: "文档结构恢复智能体",
    currentParagraphId: "p-001",
    currentParagraphIndex: 1,
    currentParagraphTotal: 6,
    currentParagraphLabel: "一、工程概况",
    currentSection: "一、工程概况",
    outlineItems: ["一、工程概况", "二、脚手架工程"],
    documentSnippets: ["工程概况已解析，识别到项目规模、工期与施工组织描述。"],
    issueSummaries: [],
  },
  {
    id: "hazard",
    stageType: "basis-binding",
    title: "危大等级判定",
    detail: "依据附录范围和项目场景判断是否触发危大/超危大程序。",
    progress: 38,
    agentKey: "construction-review",
    agentLabel: "施工方案审查智能体",
    currentParagraphId: "p-002",
    currentParagraphIndex: 2,
    currentParagraphTotal: 6,
    currentParagraphLabel: "二、脚手架工程",
    currentSection: "二、脚手架工程",
    outlineItems: ["一、工程概况", "二、脚手架工程"],
    documentSnippets: [
      "外脚手架高度 24m，触发危大工程管理校验。",
      "塔吊附着和临时用电将进入专业技术与程序合规复核。",
    ],
    issueSummaries: ["危大工程：需要专项方案审批、交底和验收闭环。"],
    hazardLabel: "危大工程 · 需程序核验",
    basisTrace: { complete: 1, partial: 1, missing: 0 },
  },
  {
    id: "basis",
    stageType: "basis-binding",
    title: "匹配审查依据",
    detail: "匹配专项施工方案编制内容、危大工程与监理审查条款。",
    progress: 46,
    agentKey: "construction-review",
    agentLabel: "施工方案审查智能体",
    currentParagraphId: "p-002",
    currentParagraphIndex: 2,
    currentParagraphTotal: 6,
    currentParagraphLabel: "二、脚手架工程",
    currentSection: "二、脚手架工程",
    outlineItems: ["一、工程概况", "二、脚手架工程", "三、塔吊安装与附着"],
    documentSnippets: [
      "脚手架章节已进入规则匹配，正在核对搭设高度与交底要求。",
      "塔吊章节已定位到安装、附着与验收相关段落。",
    ],
    issueSummaries: ["发现 1 条疑似编制内容缺项，等待语义复核。"],
    hazardLabel: "危大工程 · 需程序核验",
    basisTrace: { complete: 2, partial: 1, missing: 0 },
  },
  {
    id: "rule",
    stageType: "rule-review",
    title: "规则引擎遍历",
    detail: "执行编制内容、程序节点、签字盖章、量化阈值等确定性校验。",
    progress: 58,
    agentKey: "construction-review",
    agentLabel: "施工方案审查智能体",
    currentParagraphId: "p-003",
    currentParagraphIndex: 3,
    currentParagraphTotal: 6,
    currentParagraphLabel: "三、塔吊安装与附着",
    currentSection: "三、塔吊安装与附着",
    outlineItems: ["一、工程概况", "二、脚手架工程", "三、塔吊安装与附着"],
    documentSnippets: [
      "规则命中：脚手架工程不应按普通分项工程管理。",
      "规则命中：塔吊附着固定方式存在重大风险。",
    ],
    issueSummaries: [
      "危大工程管理方式不符合要求。",
      "塔吊附着固定方式存在重大风险。",
    ],
    hazardLabel: "危大工程 · 需程序核验",
    basisTrace: { complete: 3, partial: 1, missing: 0 },
  },
  {
    id: "semantic",
    stageType: "semantic-review",
    title: "语义审查与风险研判",
    detail: "分析措施针对性、工序逻辑与整改建议。",
    progress: 68,
    agentKey: "construction-review",
    agentLabel: "施工方案审查智能体",
    currentParagraphId: "p-004",
    currentParagraphIndex: 4,
    currentParagraphTotal: 6,
    currentParagraphLabel: "四、临时用电",
    currentSection: "四、临时用电",
    outlineItems: ["一、工程概况", "二、脚手架工程", "三、塔吊安装与附着", "四、安全管理措施"],
    documentSnippets: [
      "已识别安全管理措施章节，正在判断责任矩阵和检查频次是否可执行。",
      "正在核对临时用电、验收程序与应急措施是否形成闭环。",
    ],
    issueSummaries: [
      "脚手架搭设章节缺少验收责任主体。",
      "安全交底描述偏模板化，缺少双方签字确认要求。",
    ],
    hazardLabel: "危大工程 · 需程序核验",
    basisTrace: { complete: 3, partial: 2, missing: 0 },
  },
  {
    id: "issues",
    stageType: "issue-structuring",
    title: "生成结构化问题",
    detail: "正在生成原文锚点、依据、理由与建议修改。",
    progress: 86,
    agentKey: "construction-review",
    agentLabel: "施工方案审查智能体",
    currentParagraphId: "p-005",
    currentParagraphIndex: 5,
    currentParagraphTotal: 6,
    currentParagraphLabel: "五、应急处置",
    currentSection: "五、应急处置",
    outlineItems: ["一、工程概况", "二、脚手架工程", "三、塔吊安装与附着", "四、安全管理措施"],
    documentSnippets: [
      "已生成可回溯锚点，问题将展示在右侧意见面板。",
      "正在合并重复问题并计算风险等级。",
    ],
    issueSummaries: [
      "脚手架搭设章节缺少验收责任主体。",
      "安全交底描述偏模板化，缺少双方签字确认要求。",
      "塔吊附着验收流程缺少监理复核节点。",
    ],
    hazardLabel: "危大工程 · 需程序核验",
    basisTrace: { complete: 4, partial: 1, missing: 0 },
  },
  {
    id: "complete",
    stageType: "result-packaging",
    title: "审查结果准备完成",
    detail: "标注、依据和处理动作已准备，即将进入审查工作台。",
    progress: 100,
    agentKey: "report-generation",
    agentLabel: "审查报告生成智能体",
    currentParagraphId: "p-006",
    currentParagraphIndex: 6,
    currentParagraphTotal: 6,
    currentParagraphLabel: "六、验收与资料",
    currentSection: "六、验收与资料",
    outlineItems: ["一、工程概况", "二、脚手架工程", "三、塔吊安装与附着", "四、安全管理措施"],
    documentSnippets: [
      "AI 审查已完成。进入详情后可逐条接受、拒绝或补充人工标注。",
    ],
    issueSummaries: [
      "脚手架搭设章节缺少验收责任主体。",
      "安全交底描述偏模板化，缺少双方签字确认要求。",
      "塔吊附着验收流程缺少监理复核节点。",
      "临时用电方案缺少独立编制条件核验。",
    ],
    hazardLabel: "危大工程 · 需程序核验",
    basisTrace: { complete: 4, partial: 0, missing: 0 },
  },
];
